### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ajcksyxd** [ajcksyxd/furima-31796#9]
# URL
https://furima-31796.herokuapp.com/
# Basic認証のIDとパスワード
ID　admin　パスワード　2222
# 出品者用のメールアドレスとパスワード
email　test@test.com　パスワード　111aaa
# 購入者用のメールアドレスとパスワード
email　test2@test.com　パスワード　111aaa
# 購入用カードの番号・期限・セキュリティコード
カード番号　4242424242424242
期限　3/23
CVC　123

**Comment by mutorisa** [comment]
内野さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
